name: Breifing Dev CI/CD

on:
  pull_request:
    branches:
      - develop
    types:
      - closed
  workflow_dispatch: # (2).수동 실행도 가능하도록

jobs:
  build:
    runs-on: ubuntu-latest # (3).OS환경
    if: github.event.pull_request.merged == true